
service: lambda-cold-start
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1769
  environment:
    AJ_TEST: true

functions:
  hello:
    handler: handler.hello
    url: true

